name: Test on PR

  on:
    pull_request:
      branches: [master]

test:
    deploy:
      name: test infra on pr
      runs-on: unbuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-acess-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-acess-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      - name: IaC Apply
      env:
        COMMAND_IAC: terraform
      run: 
        cd infraestrutucture
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan